// <auto-generated />
namespace Libanon_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RemoveIsAcceptColumnFromBookBorrowingsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveIsAcceptColumnFromBookBorrowingsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202305150719444_RemoveIsAcceptColumnFromBookBorrowingsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
